import * as alt from 'alt-server';
import { useApi } from '@Server/api/index.js';
import { Item } from '@Shared/types/items.js';

declare module '@Shared/types/items.js' {
    interface RebarItems {
        [key: string]: string;
    }
}

declare module 'alt-server' {
    export interface ICustomEmitEvent {
        'inventory:useWeapon': (player: alt.Player, item: Item) => void;
        'inventory:useParachute': (player: alt.Player, item: Item) => void;
        'inventory:useFireExtinguisher': (player: alt.Player, item: Item) => void;
    }
}

export const weapons: Array<Item> = [
    // Assault Rifles
    {
        name: 'Advanced Rifle',
        desc: 'Lightweight rifle with high rate of fire.',
        id: 'weapon_advancedrifle',
        icon: '../../../images/weapon_advancedrifle.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_advancedrifle',
        weight: 6,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '30/30',
            isToolbar: true,
        },
    },
    {
        name: 'Assault Rifle',
        desc: 'Standard military assault rifle.',
        id: 'weapon_assaultrifle',
        icon: '../../../images/weapon_assaultrifle.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_assaultrifle',
        weight: 7,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '30/30',
            isToolbar: true,
        },
    },
    {
        name: 'Assault Rifle Mk II',
        desc: 'Upgraded assault rifle with enhanced features.',
        id: 'weapon_assaultrifle_mk2',
        icon: '../../../images/weapon_assaultrifle_mk2.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_assaultrifle_mk2',
        weight: 7,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '30/30',
        },
    },
    {
        name: 'Carbine Rifle',
        desc: 'High-accuracy rifle with modular design.',
        id: 'weapon_carbinerifle',
        icon: '../../../images/weapon_carbinerifle.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_carbinerifle',
        weight: 8,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '30/30',
        },
    },
    {
        name: 'Carbine Rifle Mk II',
        desc: 'Upgraded carbine rifle with enhanced features.',
        id: 'weapon_carbinerifle_mk2',
        icon: '../../../images/weapon_carbinerifle_mk2.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_carbinerifle_mk2',
        weight: 8,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '30/30',
        },
    },
    {
        name: 'Compact Rifle',
        desc: 'A smaller version of the standard assault rifle.',
        id: 'weapon_compactrifle',
        icon: '../../../images/weapon_compactrifle.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_compactrifle',
        weight: 6,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '30/30',
        },
    },
    // Pistols
    {
        name: 'AP Pistol',
        desc: 'High-penetration fully-automatic pistol.',
        id: 'weapon_appistol',
        icon: '../../../images/weapon_appistol.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_appistol',
        weight: 5,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '18/18',
        },
    },
    {
        name: 'Ceramic Pistol',
        desc: 'Lightweight pistol with a ceramic finish.',
        id: 'weapon_ceramicpistol',
        icon: '../../../images/weapon_ceramicpistol.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_ceramicpistol',
        weight: 3,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '12/12',
        },
    },
    {
        name: 'Combat Pistol',
        desc: 'Semi-automatic pistol with a detachable magazine.',
        id: 'weapon_combatpistol',
        icon: '../../../images/weapon_combatpistol.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_combatpistol',
        weight: 5,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '12/12',
        },
    },
    {
        name: 'Heavy Pistol',
        desc: 'Accurate and powerful pistol for high-damage output.',
        id: 'weapon_heavypistol',
        icon: '../../../images/weapon_heavypistol.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_heavypistol',
        weight: 5,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '18/18',
        },
    },
    {
        name: 'Pistol',
        desc: 'Standard sidearm for self-defense and law enforcement.',
        id: 'weapon_pistol',
        icon: '../../../images/weapon_pistol.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_pistol',
        weight: 5,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '12/12',
        },
    },
    {
        name: 'Pistol Mk II',
        desc: 'Upgraded pistol with enhanced features.',
        id: 'weapon_pistol_mk2',
        icon: '../../../images/weapon_pistol_mk2.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_pistol_mk2',
        weight: 5,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '12/12',
        },
    },
    {
        name: 'Pistol .50',
        desc: 'High-caliber pistol with increased stopping power.',
        id: 'weapon_pistol50',
        icon: '../../../images/weapon_pistol50.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_pistol50',
        weight: 6,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '9/9',
        },
    },
    // Submachine Guns (SMGs)
    {
        name: 'Micro SMG',
        desc: 'Compact submachine gun with high fire rate.',
        id: 'weapon_microsmg',
        icon: '../../../images/weapon_microsmg.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_microsmg',
        weight: 4,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '16/16',
        },
    },
    {
        name: 'SMG',
        desc: 'Versatile submachine gun with balanced stats.',
        id: 'weapon_smg',
        icon: '../../../images/weapon_smg.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_smg',
        weight: 5,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '30/30',
        },
    },
    {
        name: 'Combat PDW',
        desc: 'Personal defense weapon with integrated suppressor.',
        id: 'weapon_combatpdw',
        icon: '../../../images/weapon_combatpdw.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_combatpdw',
        weight: 5,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '30/30',
        },
    },
    {
        name: 'Mini SMG',
        desc: 'Small SMG with a high rate of fire.',
        id: 'weapon_minismg',
        icon: '../../../images/weapon_minismg.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_minismg',
        weight: 3,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '20/20',
        },
    },
    // Melee Weapons
    {
        name: 'Bat',
        desc: 'Wooden bat suitable for melee attacks.',
        id: 'weapon_bat',
        icon: '../../../images/weapon_bat.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_bat',
        weight: 3,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
        },
    },
    {
        name: 'Crowbar',
        desc: 'A heavy-duty crowbar for prying and melee combat.',
        id: 'weapon_crowbar',
        icon: '../../../images/weapon_crowbar.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_crowbar',
        weight: 4,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
        },
    },
    {
        name: 'Knife',
        desc: 'A sharp blade perfect for close combat.',
        id: 'weapon_knife',
        icon: '../../../images/weapon_knife.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_knife',
        weight: 1,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
        },
    },
    // Heavy Weapons
    {
        name: 'RPG',
        desc: 'Rocket-propelled grenade launcher.',
        id: 'weapon_rpg',
        icon: '../../../images/weapon_rpg.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_rpg',
        weight: 15,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '1/1',
        },
    },
    {
        name: 'Railgun',
        desc: 'Electromagnetic weapon firing hyper-velocity projectiles.',
        id: 'weapon_railgun',
        icon: '../../../images/weapon_railgun.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_railgun',
        weight: 12,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '1/1',
        },
    },
    // Shotguns
    {
        name: 'Pump Shotgun',
        desc: 'Reliable pump-action shotgun.',
        id: 'weapon_pumpshotgun',
        icon: '../../../images/weapon_pumpshotgun.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_pumpshotgun',
        weight: 9,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '8/8',
        },
    },
    {
        name: 'Pump Shotgun Mk II',
        desc: 'Upgraded pump-action shotgun with enhanced features.',
        id: 'weapon_pumpshotgun_mk2',
        icon: '../../../images/weapon_pumpshotgun_mk2.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_pumpshotgun_mk2',
        weight: 9,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '8/8',
        },
    },
    {
        name: 'Sawed-Off Shotgun',
        desc: 'Compact shotgun with wide spread.',
        id: 'weapon_sawnoffshotgun',
        icon: '../../../images/weapon_sawnoffshotgun.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_sawnoffshotgun',
        weight: 7,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '8/8',
        },
    },
    {
        name: 'Assault Shotgun',
        desc: 'Fully automatic shotgun with high fire rate.',
        id: 'weapon_assaultshotgun',
        icon: '../../../images/weapon_assaultshotgun.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_assaultshotgun',
        weight: 10,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '32/32',
        },
    },
    {
        name: 'Bullpup Shotgun',
        desc: 'High-damage shotgun with reduced recoil.',
        id: 'weapon_bullpupshotgun',
        icon: '../../../images/weapon_bullpupshotgun.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_bullpupshotgun',
        weight: 8,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '14/14',
        },
    },
    {
        name: 'Heavy Shotgun',
        desc: 'Automatic shotgun with customizable features.',
        id: 'weapon_heavyshotgun',
        icon: '../../../images/weapon_heavyshotgun.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_heavyshotgun',
        weight: 11,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '6/6',
        },
    },
    {
        name: 'Double Barrel Shotgun',
        desc: 'Classic shotgun with two barrels.',
        id: 'weapon_dbshotgun',
        icon: '../../../images/weapon_dbshotgun.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_dbshotgun',
        weight: 9,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '2/2',
        },
    },
    {
        name: 'Sweeper Shotgun',
        desc: 'Compact shotgun with high fire rate.',
        id: 'weapon_autoshotgun',
        icon: '../../../images/weapon_autoshotgun.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_autoshotgun',
        weight: 8,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '10/10',
        },
    },

    // Sniper Rifles
    {
        name: 'Sniper Rifle',
        desc: 'Long-range rifle with high accuracy.',
        id: 'weapon_sniperrifle',
        icon: '../../../images/weapon_sniperrifle.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_sniperrifle',
        weight: 10,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '10/10',
        },
    },
    {
        name: 'Heavy Sniper',
        desc: 'Anti-materiel rifle with extreme power.',
        id: 'weapon_heavysniper',
        icon: '../../../images/weapon_heavysniper.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_heavysniper',
        weight: 15,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '6/6',
        },
    },
    {
        name: 'Heavy Sniper Mk II',
        desc: 'Upgraded heavy sniper with enhanced features.',
        id: 'weapon_heavysniper_mk2',
        icon: '../../../images/weapon_heavysniper_mk2.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_heavysniper_mk2',
        weight: 15,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '6/6',
        },
    },
    {
        name: 'Marksman Rifle',
        desc: 'Semi-automatic rifle for medium to long-range.',
        id: 'weapon_marksmanrifle',
        icon: '../../../images/weapon_marksmanrifle.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_marksmanrifle',
        weight: 9,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '8/8',
        },
    },
    {
        name: 'Marksman Rifle Mk II',
        desc: 'Upgraded marksman rifle with enhanced features.',
        id: 'weapon_marksmanrifle_mk2',
        icon: '../../../images/weapon_marksmanrifle_mk2.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_marksmanrifle_mk2',
        weight: 9,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '8/8',
        },
    },

    // Heavy Weapons
    {
        name: 'Grenade Launcher',
        desc: 'Launches explosive grenades over distance.',
        id: 'weapon_grenadelauncher',
        icon: '../../../images/weapon_grenadelauncher.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_grenadelauncher',
        weight: 11,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '10/10',
        },
    },
    {
        name: 'Firework Launcher',
        desc: 'Festive launcher that shoots fireworks.',
        id: 'weapon_firework',
        icon: '../../../images/weapon_firework.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_firework',
        weight: 10,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '1/1',
        },
    },
    {
        name: 'Minigun',
        desc: 'High-rate-of-fire rotary gun.',
        id: 'weapon_minigun',
        icon: '../../../images/weapon_minigun.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_minigun',
        weight: 20,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            ammo: '500/500',
        },
    },

    // Throwables
    {
        name: 'Grenade',
        desc: 'Explosive throwable device.',
        id: 'weapon_grenade',
        icon: '../../../images/weapon_grenade.png',
        maxStack: 10,
        quantity: 1,
        uid: 'inventory_weapon_grenade',
        weight: 1,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
        },
    },
    {
        name: 'Sticky Bomb',
        desc: 'Explosive device that sticks to surfaces.',
        id: 'weapon_stickybomb',
        icon: '../../../images/weapon_stickybomb.png',
        maxStack: 10,
        quantity: 1,
        uid: 'inventory_weapon_stickybomb',
        weight: 1,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
        },
    },
    {
        name: 'Proximity Mine',
        desc: 'Explosive triggered by proximity.',
        id: 'weapon_proxmine',
        icon: '../../../images/weapon_proxmine.png',
        maxStack: 10,
        quantity: 1,
        uid: 'inventory_weapon_proxmine',
        weight: 1,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
        },
    },
    {
        name: 'Molotov Cocktail',
        desc: 'Incendiary device that sets targets on fire.',
        id: 'weapon_molotov',
        icon: '../../../images/weapon_molotov.png',
        maxStack: 10,
        quantity: 1,
        uid: 'inventory_weapon_molotov',
        weight: 1,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            fireDuration: '10s',
        },
    },
    {
        name: 'Smoke Grenade',
        desc: 'Grenade that releases smoke to obscure vision.',
        id: 'weapon_smokegrenade',
        icon: '../../../images/weapon_smokegrenade.png',
        maxStack: 10,
        quantity: 1,
        uid: 'inventory_weapon_smokegrenade',
        weight: 1,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
        },
    },
    {
        name: 'BZ Gas',
        desc: 'A potent incapacitating gas.',
        id: 'weapon_bzgas',
        icon: '../../../images/weapon_bzgas.png',
        maxStack: 10,
        quantity: 1,
        uid: 'inventory_weapon_bzgas',
        weight: 1,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
        },
    },
    {
        name: 'Ball',
        desc: 'A throwable ball. Fun for games.',
        id: 'weapon_ball',
        icon: '../../../images/weapon_ball.png',
        maxStack: 10,
        quantity: 1,
        uid: 'inventory_weapon_ball',
        weight: 1,
        useEventName: 'inventory:useWeapon',
        data: {},
    },
    {
        name: 'Snowball',
        desc: 'A ball of snow, perfect for a snowball fight.',
        id: 'weapon_snowball',
        icon: '../../../images/weapon_snowball.png',
        maxStack: 10,
        quantity: 1,
        uid: 'inventory_weapon_snowball',
        weight: 1,
        useEventName: 'inventory:useWeapon',
        data: {},
    },
    {
        name: 'Tear Gas',
        desc: 'Grenade that releases tear gas.',
        id: 'weapon_teargas',
        icon: '../../../images/weapon_teargas.png',
        maxStack: 10,
        quantity: 1,
        uid: 'inventory_weapon_teargas',
        weight: 1,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
        },
    },
    {
        name: 'Jerry Can',
        desc: 'Container of gasoline that can be poured and ignited.',
        id: 'weapon_petrolcan',
        icon: '../../../images/weapon_petrolcan.png',
        maxStack: 1,
        quantity: 1,
        uid: 'inventory_weapon_petrolcan',
        weight: 5,
        useEventName: 'inventory:useWeapon',
        data: {
            condition: 100,
            fuelLevel: '100%',
        },
    },
];

// Register all weapons with the ItemManager
const ItemManager = await useApi().getAsync('item-manager-api');
for (const item of weapons) {
    ItemManager.useItemManager().create(item);
}
